version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: secret

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  app:
    depends_on: 
      - db
    build:
      dockerfile: Dockerfile
    restart: always
    ports: 
      - 3000:3000
